apiVersion: v1
kind: Secret
metadata:
    name: headscale-secrets
    namespace: headscale
stringData:
    key: ENC[AES256_GCM,data:p4qdmgXFrdgy39xofKLZ3WV4+nmUkwo7sUjMihuNUHqYlKIUKoikxNJwcis=,iv:uVjMDI+8Z0VOrZ1XMyoCUYjvIW00l2T30r19/jZLtf4=,tag:cB9JjRUF4HE2LvorqNib6g==,type:str]
    username: ENC[AES256_GCM,data:I81ydJ0=,iv:0S2fKOVvl0odkx7TC5Phi+id8SCcNg0dTdow6fdmk2k=,tag:u88BeO1GCByRi65cFRyoSA==,type:str]
    password: ENC[AES256_GCM,data:OhFCpOD6saFKVHWHuRm8,iv:OU95gwYOtsyDKkEEMqeF3pT13qZ8YcIbacfcJlySx5M=,tag:bupQtinXeDQAPrBOvm9PAQ==,type:str]
    oidc-client-id: ENC[AES256_GCM,data:quIEFDhGPm7q,iv:UEip3c/YL93VkNvDG0T9Y/i951lqJa0dUGRBITlvbLE=,tag:TtQPPssABMVSNgRE7JfFEQ==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:PM7aqJ09KkliAGacCOWtS7GjAappUim86EGeUcCwa8w=,iv:8kv1XKPlyC3yrdNZ+X8/kQJGwcHBpnbtPKl8n8IJeH8=,tag:7v74z5ZkmmPYtus2YzXfiw==,type:str]
    oidc-headscale-webui-client-id: ENC[AES256_GCM,data:Fkhy7Ats1PutfkpwqMkx,iv:dD5+TRsCr87yUCTxrCSlc6LdaV+7vLZfPoFO8dNgxNo=,tag:yIBlwrg1XhuPfhSwzpdKAQ==,type:str]
    oidc-headscale-webui-client-secret: ENC[AES256_GCM,data:mMk5+5ElHNa9CAUSOnVhx2Iy0kXtECe99did6LxeXT4=,iv:GT4RtojrN92nfy4kb1l8P4cNwvv40+e7aXSS9auRtEA=,tag:tvBTDzFfSOzxx6KNKsP+fQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mfp32e7fyypeyfcp6x2zhh4hkym9ra6fyv3g4p7n3klrepefx3ns7uq276
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJc0RnUzA5OVQ3R3BqcTZO
            OS9XTm0zZ0lKU2wwQmwxd21vNnVCM2RZL0NFCjhVdkY3NFV0c0RCK1JWeTRPSVVX
            dmJMVWVwbFAzanYrUlF0RnAvb2JmS2sKLS0tIHRQZlN0YkNieWxKL2srQ3ZxK0tY
            d3cwT1Zuc2hmOStqallhMHlianN0d00Kt+CHIkIZCQbJsfcNgT8hVSUrbTJyMsV6
            Gg2BSAgYK+4zSnkM8KqAF/nKh2vPnHlMyx/Xwcr5wrP1lJzvwfQUgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-19T12:02:07Z"
    mac: ENC[AES256_GCM,data:UrYfYZnR4nHtq8cO01aJYdD/pRBrA8zi21jNhP7DhkGstQ0WUN/FC1BFOZXZ1ZnB5ePMSFNOBLVZYCNRHbPyVuYw2wl0f/ls9tokFwIQa7adgI5mTW9mCRgQ6Y6UBBWI+1iVMl7RCEV9aZg0cb3ShhE7po18uHL6qwH3GsEqszE=,iv:yc6ywySLdcAvEvGC+uN1NMQRg5j3IbV4csMorZpBgVc=,tag:xBDuPsOSi1CHthCzjj0WNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
